import "./globals.css";

export const metadata = {
  title: "Landing Page",
  description: "Landing Page Generated by Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="universNormal">{children}</body>
    </html>
  );
}
